### ISSUE TITLE
Delete set-syssetting

### ISSUE THREAD

**Issue by keithschm** [Academy-Creatio/Nov_2021_Training#7]
I believe I put a bad entry in while setting up the Exchange stuff using clio. Is there a way delete or see the settings? The documentation is not clear.

I am unable to run clio restart as I get an Error:
System.UriFormatException: Invalid URI: The format of the URI could not be determined.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at System.Uri..ctor(String uriString)
   at System.Net.WebRequest.Create(String requestUriString)
   at Creatio.Client.CreatioClient.CreateRequest(String url, String requestData)
   at Creatio.Client.CreatioClient.Login()
   at Creatio.Client.CreatioClient.CreateCreatioRequest(String url, String requestData, Int32 requestTimeout)
   at Creatio.Client.CreatioClient.ExecutePostRequest(String url, String requestData, Int32 requestTimeout)
   at Clio.Common.CreatioClientAdapter.ExecutePostRequest(String url, String requestData, Int32 requestTimeout)
   at Clio.Command.RemoteCommand`1.ExecuteRemoteCommand(TEnvironmentOptions options)
   at Clio.Command.RemoteCommand`1.Execute(TEnvironmentOptions options)

Thanks all

**Comment by kirillkrylov** [comment]
execute the following in a terminal. Open appsettings.json and remove whatever environment you wish to delete.

`clio apps`
![image](https://user-images.githubusercontent.com/7285114/145977888-62725461-3269-4608-83bb-d0e89c39bb01.png)
